trigger:
- main  # Define the branch to trigger the pipeline

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      installationPath: $(Agent.ToolsDirectory)/dotnet
      version: '3.1.2'  # Choose the appropriate version

  - script: dotnet restore
    displayName: 'Restore NuGet Packages'

  - script: dotnet build --configuration Release
    displayName: 'Build Solution'
